package net.mcreator.yafnafmod.block.listener;

import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.client.event.EntityRenderersEvent;
import net.minecraftforge.api.distmarker.OnlyIn;
import net.minecraftforge.api.distmarker.Dist;

import net.mcreator.yafnafmod.init.YaFnafmodModBlockEntities;
import net.mcreator.yafnafmod.block.renderer.WitheredFreddyBlockTileRenderer;
import net.mcreator.yafnafmod.block.renderer.WitheredFoxyBlockTileRenderer;
import net.mcreator.yafnafmod.block.renderer.WitheredChicaBlockTileRenderer;
import net.mcreator.yafnafmod.block.renderer.WitheredBonnieBlockTileRenderer;
import net.mcreator.yafnafmod.block.renderer.VanRideTileRenderer;
import net.mcreator.yafnafmod.block.renderer.TrashTileRenderer;
import net.mcreator.yafnafmod.block.renderer.TrashCanMeshTileRenderer;
import net.mcreator.yafnafmod.block.renderer.TrashCanFreddyTileRenderer;
import net.mcreator.yafnafmod.block.renderer.TrashCanFoxyTileRenderer;
import net.mcreator.yafnafmod.block.renderer.TrashCanCupcakeTileRenderer;
import net.mcreator.yafnafmod.block.renderer.TrashCanChicaTileRenderer;
import net.mcreator.yafnafmod.block.renderer.TrashCanBonnieTileRenderer;
import net.mcreator.yafnafmod.block.renderer.TrashBagGreenTileRenderer;
import net.mcreator.yafnafmod.block.renderer.TrashBagBlackTileRenderer;
import net.mcreator.yafnafmod.block.renderer.ToypugTileRenderer;
import net.mcreator.yafnafmod.block.renderer.ToyFreddyBlockTileRenderer;
import net.mcreator.yafnafmod.block.renderer.ToyFoxyBlockTileRenderer;
import net.mcreator.yafnafmod.block.renderer.ToyChicaChickenBlockTileRenderer;
import net.mcreator.yafnafmod.block.renderer.ToyBonnieBlockTileRenderer;
import net.mcreator.yafnafmod.block.renderer.StarArchTileRenderer;
import net.mcreator.yafnafmod.block.renderer.StageSunCreepTileRenderer;
import net.mcreator.yafnafmod.block.renderer.StageMoonCreepTileRenderer;
import net.mcreator.yafnafmod.block.renderer.StageLightYellowTileRenderer;
import net.mcreator.yafnafmod.block.renderer.StageLightRedTileRenderer;
import net.mcreator.yafnafmod.block.renderer.StageLightPurpleTileRenderer;
import net.mcreator.yafnafmod.block.renderer.StageLightPinkTileRenderer;
import net.mcreator.yafnafmod.block.renderer.StageLightOrangeTileRenderer;
import net.mcreator.yafnafmod.block.renderer.StageLightGreenTileRenderer;
import net.mcreator.yafnafmod.block.renderer.StageLightBlueTileRenderer;
import net.mcreator.yafnafmod.block.renderer.SpringbonnieHeadTileRenderer;
import net.mcreator.yafnafmod.block.renderer.SpringbonnieBlockTileRenderer;
import net.mcreator.yafnafmod.block.renderer.SpringbonnieBlock01TileRenderer;
import net.mcreator.yafnafmod.block.renderer.SkeeballPizzarollerTileRenderer;
import net.mcreator.yafnafmod.block.renderer.SkeeballGenericTileRenderer;
import net.mcreator.yafnafmod.block.renderer.SinkKitchenTileRenderer;
import net.mcreator.yafnafmod.block.renderer.ShopSignStansBudgetTechTileRenderer;
import net.mcreator.yafnafmod.block.renderer.ShopSignSmilesAndServosTileRenderer;
import net.mcreator.yafnafmod.block.renderer.ShopSignRareFindsAuctionTileRenderer;
import net.mcreator.yafnafmod.block.renderer.ShopSignDumpsterDiverTileRenderer;
import net.mcreator.yafnafmod.block.renderer.SecurityPuppetPropTileRenderer;
import net.mcreator.yafnafmod.block.renderer.ScooperTileRenderer;
import net.mcreator.yafnafmod.block.renderer.SanitationStationTileRenderer;
import net.mcreator.yafnafmod.block.renderer.RustyBlockTileRenderer;
import net.mcreator.yafnafmod.block.renderer.RosieTileRenderer;
import net.mcreator.yafnafmod.block.renderer.RockstarFreddyBlockTileRenderer;
import net.mcreator.yafnafmod.block.renderer.RockstarFoxyBlockTileRenderer;
import net.mcreator.yafnafmod.block.renderer.RockstarChicaBlockTileRenderer;
import net.mcreator.yafnafmod.block.renderer.RockstarBonnieBlockTileRenderer;
import net.mcreator.yafnafmod.block.renderer.RidingRocketRedTileRenderer;
import net.mcreator.yafnafmod.block.renderer.RidingRocketPurpleTileRenderer;
import net.mcreator.yafnafmod.block.renderer.RetroFreddyBlockTileRenderer;
import net.mcreator.yafnafmod.block.renderer.RetroFoxyBlockTileRenderer;
import net.mcreator.yafnafmod.block.renderer.RetroChicaBlockTileRenderer;
import net.mcreator.yafnafmod.block.renderer.RetroBonnieBlockTileRenderer;
import net.mcreator.yafnafmod.block.renderer.RascBlockTileRenderer;
import net.mcreator.yafnafmod.block.renderer.PuppetBlockTileRenderer;
import net.mcreator.yafnafmod.block.renderer.ProjectorTileRenderer;
import net.mcreator.yafnafmod.block.renderer.PrizeKingTileRenderer;
import net.mcreator.yafnafmod.block.renderer.PotTileRenderer;
import net.mcreator.yafnafmod.block.renderer.PlushFingertrapTileRenderer;
import net.mcreator.yafnafmod.block.renderer.PizzeriaSignMovieTileRenderer;
import net.mcreator.yafnafmod.block.renderer.PizzeriaSignMovie2TileRenderer;
import net.mcreator.yafnafmod.block.renderer.PizzeriaSignFrightsTileRenderer;
import net.mcreator.yafnafmod.block.renderer.PizzeriaSignFredbearsTileRenderer;
import net.mcreator.yafnafmod.block.renderer.PizzeriaSignFredbearsAltTileRenderer;
import net.mcreator.yafnafmod.block.renderer.PizzeriaSignFfpsTileRenderer;
import net.mcreator.yafnafmod.block.renderer.PizzeriaSignChicasTileRenderer;
import net.mcreator.yafnafmod.block.renderer.PizzeriaSignBabysTileRenderer;
import net.mcreator.yafnafmod.block.renderer.PizzeriaSignBabysAltTileRenderer;
import net.mcreator.yafnafmod.block.renderer.PizzeriaSign1988TileRenderer;
import net.mcreator.yafnafmod.block.renderer.PizzeriaSign1987TileRenderer;
import net.mcreator.yafnafmod.block.renderer.PizzaBoxStack2023TileRenderer;
import net.mcreator.yafnafmod.block.renderer.PizzaBoxStack1988TileRenderer;
import net.mcreator.yafnafmod.block.renderer.PizzaBoxStack1987TileRenderer;
import net.mcreator.yafnafmod.block.renderer.PizzaBoxStack1987AltTileRenderer;
import net.mcreator.yafnafmod.block.renderer.PizzaBoxStack1985TileRenderer;
import net.mcreator.yafnafmod.block.renderer.PizzaBoxStack1979TileRenderer;
import net.mcreator.yafnafmod.block.renderer.PizzaBox2023TileRenderer;
import net.mcreator.yafnafmod.block.renderer.PizzaBox2023EmptyTileRenderer;
import net.mcreator.yafnafmod.block.renderer.PizzaBox1988TileRenderer;
import net.mcreator.yafnafmod.block.renderer.PizzaBox1988EmptyTileRenderer;
import net.mcreator.yafnafmod.block.renderer.PizzaBox1987TileRenderer;
import net.mcreator.yafnafmod.block.renderer.PizzaBox1987EmptyTileRenderer;
import net.mcreator.yafnafmod.block.renderer.PizzaBox1987AltTileRenderer;
import net.mcreator.yafnafmod.block.renderer.PizzaBox1987AltEmptyTileRenderer;
import net.mcreator.yafnafmod.block.renderer.PizzaBox1985TileRenderer;
import net.mcreator.yafnafmod.block.renderer.PizzaBox1985EmptyTileRenderer;
import net.mcreator.yafnafmod.block.renderer.PizzaBox1979TileRenderer;
import net.mcreator.yafnafmod.block.renderer.PizzaBox1979EmptyTileRenderer;
import net.mcreator.yafnafmod.block.renderer.PinballToyFreddyTileRenderer;
import net.mcreator.yafnafmod.block.renderer.PinballToyFoxyTileRenderer;
import net.mcreator.yafnafmod.block.renderer.PinballToyChicaTileRenderer;
import net.mcreator.yafnafmod.block.renderer.PinballToyBonnieTileRenderer;
import net.mcreator.yafnafmod.block.renderer.PinTheBowtieToyFreddyTileRenderer;
import net.mcreator.yafnafmod.block.renderer.PinTheBowtieFreddyTileRenderer;
import net.mcreator.yafnafmod.block.renderer.PigpatchBlockTileRenderer;
import net.mcreator.yafnafmod.block.renderer.PiecesFuntimeFreddyTileRenderer;
import net.mcreator.yafnafmod.block.renderer.PiecesFuntimeFoxyTileRenderer;
import net.mcreator.yafnafmod.block.renderer.PiecesBalloraTileRenderer;
import net.mcreator.yafnafmod.block.renderer.PartsBoxTileRenderer;
import net.mcreator.yafnafmod.block.renderer.OrvilleElephantBlockTileRenderer;
import net.mcreator.yafnafmod.block.renderer.OldManConsequencesBlockTileRenderer;
import net.mcreator.yafnafmod.block.renderer.OfficeChairRedTileRenderer;
import net.mcreator.yafnafmod.block.renderer.OfficeChairBlackTileRenderer;
import net.mcreator.yafnafmod.block.renderer.NoveltyTrafficLightTileRenderer;
import net.mcreator.yafnafmod.block.renderer.NeonStageLightPinkTileRenderer;
import net.mcreator.yafnafmod.block.renderer.NeonStageLightOrangeTileRenderer;
import net.mcreator.yafnafmod.block.renderer.NeonStageLightGreenTileRenderer;
import net.mcreator.yafnafmod.block.renderer.NeonStageLightBlueTileRenderer;
import net.mcreator.yafnafmod.block.renderer.NeonSignRestroomTileRenderer;
import net.mcreator.yafnafmod.block.renderer.NeonSignPartyRoomTileRenderer;
import net.mcreator.yafnafmod.block.renderer.NeonSignKitchenTileRenderer;
import net.mcreator.yafnafmod.block.renderer.NeonSignArcadeTileRenderer;
import net.mcreator.yafnafmod.block.renderer.NeonJukeboxTileRenderer;
import net.mcreator.yafnafmod.block.renderer.NeddbearBlockTileRenderer;
import net.mcreator.yafnafmod.block.renderer.MusicBoxDecorationTileRenderer;
import net.mcreator.yafnafmod.block.renderer.MrHippoBlockTileRenderer;
import net.mcreator.yafnafmod.block.renderer.MedicalStationTileRenderer;
import net.mcreator.yafnafmod.block.renderer.MangleBlockTileRenderer;
import net.mcreator.yafnafmod.block.renderer.LeftyBlockTileRenderer;
import net.mcreator.yafnafmod.block.renderer.LargeFanTileRenderer;
import net.mcreator.yafnafmod.block.renderer.LaptopTileRenderer;
import net.mcreator.yafnafmod.block.renderer.LaptopOldTileRenderer;
import net.mcreator.yafnafmod.block.renderer.LadderTowerTileRenderer;
import net.mcreator.yafnafmod.block.renderer.HappyFrogBlockTileRenderer;
import net.mcreator.yafnafmod.block.renderer.GravityVortexTileRenderer;
import net.mcreator.yafnafmod.block.renderer.GrandfatherClockTileRenderer;
import net.mcreator.yafnafmod.block.renderer.GarfeldTileRenderer;
import net.mcreator.yafnafmod.block.renderer.FuntimeFreddyBlockTileRenderer;
import net.mcreator.yafnafmod.block.renderer.FuntimeDelilahBlockTileRenderer;
import net.mcreator.yafnafmod.block.renderer.FryingPanTileRenderer;
import net.mcreator.yafnafmod.block.renderer.FryerTileRenderer;
import net.mcreator.yafnafmod.block.renderer.FridgeWhiteTileRenderer;
import net.mcreator.yafnafmod.block.renderer.FridgeIndustrialTileRenderer;
import net.mcreator.yafnafmod.block.renderer.FridgeGrayTileRenderer;
import net.mcreator.yafnafmod.block.renderer.FreddyStandTileRenderer;
import net.mcreator.yafnafmod.block.renderer.FreddyHeadTileRenderer;
import net.mcreator.yafnafmod.block.renderer.FreddyFazbearBlockTileRenderer;
import net.mcreator.yafnafmod.block.renderer.FredbearHeadTileRenderer;
import net.mcreator.yafnafmod.block.renderer.FredbearBloodyWrapBlockTileRenderer;
import net.mcreator.yafnafmod.block.renderer.FredbearBloodyBlockTileRenderer;
import net.mcreator.yafnafmod.block.renderer.FredbearBlockTileRenderer;
import net.mcreator.yafnafmod.block.renderer.Fredbear01BlockTileRenderer;
import net.mcreator.yafnafmod.block.renderer.FoxyStandTileRenderer;
import net.mcreator.yafnafmod.block.renderer.FoxyPirateFixedBlockTileRenderer;
import net.mcreator.yafnafmod.block.renderer.FoxyPirateBlockTileRenderer;
import net.mcreator.yafnafmod.block.renderer.FoxyHeadTileRenderer;
import net.mcreator.yafnafmod.block.renderer.Fazcoins5TileRenderer;
import net.mcreator.yafnafmod.block.renderer.Fazcoins25TileRenderer;
import net.mcreator.yafnafmod.block.renderer.Fazcoins100TileRenderer;
import net.mcreator.yafnafmod.block.renderer.Fazcoins1000TileRenderer;
import net.mcreator.yafnafmod.block.renderer.Fazcoins10000TileRenderer;
import net.mcreator.yafnafmod.block.renderer.FazOvenTileRenderer;
import net.mcreator.yafnafmod.block.renderer.ExoticButterBasketTileRenderer;
import net.mcreator.yafnafmod.block.renderer.EnhancedSpeakerTileRenderer;
import net.mcreator.yafnafmod.block.renderer.Endo02BlockTileRenderer;
import net.mcreator.yafnafmod.block.renderer.Endo01PropTileRenderer;
import net.mcreator.yafnafmod.block.renderer.Endo01BlockTileRenderer;
import net.mcreator.yafnafmod.block.renderer.EmptyExoticButterBasketTileRenderer;
import net.mcreator.yafnafmod.block.renderer.EggBabyTileRenderer;
import net.mcreator.yafnafmod.block.renderer.DumpsterGreenTileRenderer;
import net.mcreator.yafnafmod.block.renderer.DumpsterBlueTileRenderer;
import net.mcreator.yafnafmod.block.renderer.DuckPondTileRenderer;
import net.mcreator.yafnafmod.block.renderer.DittophobiaFreddyBlockTileRenderer;
import net.mcreator.yafnafmod.block.renderer.DittophobiaFoxyBlockTileRenderer;
import net.mcreator.yafnafmod.block.renderer.DittophobiaChicaBlockTileRenderer;
import net.mcreator.yafnafmod.block.renderer.DittophobiaBonnieBlockTileRenderer;
import net.mcreator.yafnafmod.block.renderer.DiscountCoolingUnitTileRenderer;
import net.mcreator.yafnafmod.block.renderer.DiscountBallpitTileRenderer;
import net.mcreator.yafnafmod.block.renderer.DeluxeSpeakerTileRenderer;
import net.mcreator.yafnafmod.block.renderer.DeluxeBallpitTileRenderer;
import net.mcreator.yafnafmod.block.renderer.DeactivatedFuntimeFreddyTileRenderer;
import net.mcreator.yafnafmod.block.renderer.DeactivatedBalloraTileRenderer;
import net.mcreator.yafnafmod.block.renderer.DeactivatedBabyTileRenderer;
import net.mcreator.yafnafmod.block.renderer.CutoutTreePineTileRenderer;
import net.mcreator.yafnafmod.block.renderer.CutoutTreePalmTileRenderer;
import net.mcreator.yafnafmod.block.renderer.CutoutTreeOakTileRenderer;
import net.mcreator.yafnafmod.block.renderer.CutoutSpringbonnieTileRenderer;
import net.mcreator.yafnafmod.block.renderer.CutoutSpringbonnieRottenTileRenderer;
import net.mcreator.yafnafmod.block.renderer.CutoutHelpyTileRenderer;
import net.mcreator.yafnafmod.block.renderer.CutoutFreddyToyTileRenderer;
import net.mcreator.yafnafmod.block.renderer.CutoutFreddyRetroTileRenderer;
import net.mcreator.yafnafmod.block.renderer.CutoutFreddyFuntimeTileRenderer;
import net.mcreator.yafnafmod.block.renderer.CutoutFredbearTileRenderer;
import net.mcreator.yafnafmod.block.renderer.CutoutFredbearIcecreamTileRenderer;
import net.mcreator.yafnafmod.block.renderer.CutoutFredbearBittenTileRenderer;
import net.mcreator.yafnafmod.block.renderer.CutoutFoxyRetroTileRenderer;
import net.mcreator.yafnafmod.block.renderer.CutoutFoxyFuntimeTileRenderer;
import net.mcreator.yafnafmod.block.renderer.CutoutChicaToyTileRenderer;
import net.mcreator.yafnafmod.block.renderer.CutoutChicaRetroTileRenderer;
import net.mcreator.yafnafmod.block.renderer.CutoutBonnieToyTileRenderer;
import net.mcreator.yafnafmod.block.renderer.CutoutBonnieRetroTileRenderer;
import net.mcreator.yafnafmod.block.renderer.CutoutBalloraTileRenderer;
import net.mcreator.yafnafmod.block.renderer.CutoutBabyTileRenderer;
import net.mcreator.yafnafmod.block.renderer.ControlPanelTileRenderer;
import net.mcreator.yafnafmod.block.renderer.ConcertSpeakerTileRenderer;
import net.mcreator.yafnafmod.block.renderer.ClownLemonadeTileRenderer;
import net.mcreator.yafnafmod.block.renderer.ClownFruitPunchTileRenderer;
import net.mcreator.yafnafmod.block.renderer.ClockWallToyFreddyTileRenderer;
import net.mcreator.yafnafmod.block.renderer.ClockWallToyFoxyTileRenderer;
import net.mcreator.yafnafmod.block.renderer.ClockWallToyChicaTileRenderer;
import net.mcreator.yafnafmod.block.renderer.ClockWallToyBonnieTileRenderer;
import net.mcreator.yafnafmod.block.renderer.ClockWallTileRenderer;
import net.mcreator.yafnafmod.block.renderer.ClockWallSpringbonnieTileRenderer;
import net.mcreator.yafnafmod.block.renderer.ClockWallFreddyTileRenderer;
import net.mcreator.yafnafmod.block.renderer.ClockWallFredbearTileRenderer;
import net.mcreator.yafnafmod.block.renderer.ClockWallFoxyTileRenderer;
import net.mcreator.yafnafmod.block.renderer.ClockWallChicaTileRenderer;
import net.mcreator.yafnafmod.block.renderer.ClockWallBonnieTileRenderer;
import net.mcreator.yafnafmod.block.renderer.ClawMachinePizzaPartyTileRenderer;
import net.mcreator.yafnafmod.block.renderer.ClawMachineCupcakeBonanzaTileRenderer;
import net.mcreator.yafnafmod.block.renderer.CircusBabyClockTileRenderer;
import net.mcreator.yafnafmod.block.renderer.CircusBabyBlockTileRenderer;
import net.mcreator.yafnafmod.block.renderer.ChicaStandTileRenderer;
import net.mcreator.yafnafmod.block.renderer.ChicaHeadTileRenderer;
import net.mcreator.yafnafmod.block.renderer.ChicaChickenBlockTileRenderer;
import net.mcreator.yafnafmod.block.renderer.CarouselTileRenderer;
import net.mcreator.yafnafmod.block.renderer.CarouselFreddyToyTileRenderer;
import net.mcreator.yafnafmod.block.renderer.CarouselFreddyTileRenderer;
import net.mcreator.yafnafmod.block.renderer.CarouselFreddyRetroTileRenderer;
import net.mcreator.yafnafmod.block.renderer.CarouselFredbearTileRenderer;
import net.mcreator.yafnafmod.block.renderer.CarnivalHoopsTileRenderer;
import net.mcreator.yafnafmod.block.renderer.CarStationWagonBlockTileRenderer;
import net.mcreator.yafnafmod.block.renderer.CarPurpleChevroletImpalaBlockTileRenderer;
import net.mcreator.yafnafmod.block.renderer.CarPoliceCruiserChevroletImpala1983BlockTileRenderer;
import net.mcreator.yafnafmod.block.renderer.CarHarleyMotorcycleBlockTileRenderer;
import net.mcreator.yafnafmod.block.renderer.CarFazvanPropTileRenderer;
import net.mcreator.yafnafmod.block.renderer.CarFazvanBlockTileRenderer;
import net.mcreator.yafnafmod.block.renderer.CarDodgeRam1982BlockTileRenderer;
import net.mcreator.yafnafmod.block.renderer.CandyCadetTileRenderer;
import net.mcreator.yafnafmod.block.renderer.CameraTileRenderer;
import net.mcreator.yafnafmod.block.renderer.BulletinBoardTileRenderer;
import net.mcreator.yafnafmod.block.renderer.BrokenFreddyTileRenderer;
import net.mcreator.yafnafmod.block.renderer.BrokenFoxyTileRenderer;
import net.mcreator.yafnafmod.block.renderer.BrokenChicaTileRenderer;
import net.mcreator.yafnafmod.block.renderer.BrokenBonnieTileRenderer;
import net.mcreator.yafnafmod.block.renderer.BreakerControlTileRenderer;
import net.mcreator.yafnafmod.block.renderer.BoxPlush4TileRenderer;
import net.mcreator.yafnafmod.block.renderer.BoxPlush3TileRenderer;
import net.mcreator.yafnafmod.block.renderer.BoxPlush2TileRenderer;
import net.mcreator.yafnafmod.block.renderer.BoxPlush1TileRenderer;
import net.mcreator.yafnafmod.block.renderer.BoxPlatesTileRenderer;
import net.mcreator.yafnafmod.block.renderer.BoxEndoTileRenderer;
import net.mcreator.yafnafmod.block.renderer.BonnieStandTileRenderer;
import net.mcreator.yafnafmod.block.renderer.BonnieHeadTileRenderer;
import net.mcreator.yafnafmod.block.renderer.BonnieBunnyBlockTileRenderer;
import net.mcreator.yafnafmod.block.renderer.BonkABonTileRenderer;
import net.mcreator.yafnafmod.block.renderer.Bobbleheads1TileRenderer;
import net.mcreator.yafnafmod.block.renderer.BlastSecurityDoorTileRenderer;
import net.mcreator.yafnafmod.block.renderer.BigSecurityDoorTileRenderer;
import net.mcreator.yafnafmod.block.renderer.BigRentalWindowedDoorTileRenderer;
import net.mcreator.yafnafmod.block.renderer.BigRentalDoorTileRenderer;
import net.mcreator.yafnafmod.block.renderer.BigOfficeDoorWindowed2TileRenderer;
import net.mcreator.yafnafmod.block.renderer.BigOfficeDoorWindowed1TileRenderer;
import net.mcreator.yafnafmod.block.renderer.BigKitchenWhiteDoorWideTileRenderer;
import net.mcreator.yafnafmod.block.renderer.BigKitchenWhiteDoorTileRenderer;
import net.mcreator.yafnafmod.block.renderer.BigKitchenDoorWideTileRenderer;
import net.mcreator.yafnafmod.block.renderer.BigKitchenDoorTileRenderer;
import net.mcreator.yafnafmod.block.renderer.BigFanTileRenderer;
import net.mcreator.yafnafmod.block.renderer.BigExitDoorTileRenderer;
import net.mcreator.yafnafmod.block.renderer.BigEntranceRedGlassDoorWideTileRenderer;
import net.mcreator.yafnafmod.block.renderer.BigEntranceRedGlassDoorTileRenderer;
import net.mcreator.yafnafmod.block.renderer.BigEntranceRedDoorWideTileRenderer;
import net.mcreator.yafnafmod.block.renderer.BigEntranceRedDoorTileRenderer;
import net.mcreator.yafnafmod.block.renderer.BigEntranceDoorWideTileRenderer;
import net.mcreator.yafnafmod.block.renderer.BigEntranceDoorTileRenderer;
import net.mcreator.yafnafmod.block.renderer.BigElevatorDoorTileRenderer;
import net.mcreator.yafnafmod.block.renderer.BigClosetTileRenderer;
import net.mcreator.yafnafmod.block.renderer.BigBedroomDoorTileRenderer;
import net.mcreator.yafnafmod.block.renderer.BigBackstageRedDoorWideTileRenderer;
import net.mcreator.yafnafmod.block.renderer.BigBackstageDoorTileRenderer;
import net.mcreator.yafnafmod.block.renderer.BigBackstageDoorRedTileRenderer;
import net.mcreator.yafnafmod.block.renderer.BigBackstageDoor2TileRenderer;
import net.mcreator.yafnafmod.block.renderer.BathroomStallTileRenderer;
import net.mcreator.yafnafmod.block.renderer.BarryPolarBlockTileRenderer;
import net.mcreator.yafnafmod.block.renderer.BallpitVintageTileRenderer;
import net.mcreator.yafnafmod.block.renderer.BallpitTowerTileRenderer;
import net.mcreator.yafnafmod.block.renderer.BallpitRottenTileRenderer;
import net.mcreator.yafnafmod.block.renderer.BalloraBlockTileRenderer;
import net.mcreator.yafnafmod.block.renderer.BalloonCartTileRenderer;
import net.mcreator.yafnafmod.block.renderer.BalloonBarrelTileRenderer;
import net.mcreator.yafnafmod.block.renderer.ArcadeMidnightMotoristTileRenderer;
import net.mcreator.yafnafmod.block.renderer.ArcadeFruityMazeTileRenderer;
import net.mcreator.yafnafmod.YaFnafmodMod;

@Mod.EventBusSubscriber(modid = YaFnafmodMod.MODID, bus = Mod.EventBusSubscriber.Bus.MOD)
public class ClientListener {
	@OnlyIn(Dist.CLIENT)
	@SubscribeEvent
	public static void registerRenderers(EntityRenderersEvent.RegisterRenderers event) {
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.FREDDY_HEAD.get(), context -> new FreddyHeadTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.BONNIE_HEAD.get(), context -> new BonnieHeadTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.CHICA_HEAD.get(), context -> new ChicaHeadTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.FOXY_HEAD.get(), context -> new FoxyHeadTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.MUSIC_BOX_DECORATION.get(), context -> new MusicBoxDecorationTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.CAROUSEL.get(), context -> new CarouselTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.FREDDY_STAND.get(), context -> new FreddyStandTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.BONNIE_STAND.get(), context -> new BonnieStandTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.CHICA_STAND.get(), context -> new ChicaStandTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.FOXY_STAND.get(), context -> new FoxyStandTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.PIZZERIA_SIGN_1988.get(), context -> new PizzeriaSign1988TileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.PARTS_BOX.get(), context -> new PartsBoxTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.BOBBLEHEADS_1.get(), context -> new Bobbleheads1TileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.ENDO_01_PROP.get(), context -> new Endo01PropTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.PIZZA_BOX_1988.get(), context -> new PizzaBox1988TileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.GRANDFATHER_CLOCK.get(), context -> new GrandfatherClockTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.FREDBEAR_HEAD.get(), context -> new FredbearHeadTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.SPRINGBONNIE_HEAD.get(), context -> new SpringbonnieHeadTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.CUTOUT_FREDBEAR.get(), context -> new CutoutFredbearTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.CUTOUT_SPRINGBONNIE.get(), context -> new CutoutSpringbonnieTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.PIZZERIA_SIGN_FREDBEARS_ALT.get(), context -> new PizzeriaSignFredbearsAltTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.PLUSH_FINGERTRAP.get(), context -> new PlushFingertrapTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.PIZZA_BOX_1979.get(), context -> new PizzaBox1979TileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.PIZZA_BOX_1988_EMPTY.get(), context -> new PizzaBox1988EmptyTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.PIZZA_BOX_1979_EMPTY.get(), context -> new PizzaBox1979EmptyTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.BIG_FAN.get(), context -> new BigFanTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.FREDDY_FAZBEAR_BLOCK.get(), context -> new FreddyFazbearBlockTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.BARRY_POLAR_BLOCK.get(), context -> new BarryPolarBlockTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.BONNIE_BUNNY_BLOCK.get(), context -> new BonnieBunnyBlockTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.FOXY_PIRATE_BLOCK.get(), context -> new FoxyPirateBlockTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.FOXY_PIRATE_FIXED_BLOCK.get(), context -> new FoxyPirateFixedBlockTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.TOY_FREDDY_BLOCK.get(), context -> new ToyFreddyBlockTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.TOY_BONNIE_BLOCK.get(), context -> new ToyBonnieBlockTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.MANGLE_BLOCK.get(), context -> new MangleBlockTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.CHICA_CHICKEN_BLOCK.get(), context -> new ChicaChickenBlockTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.TOY_CHICA_CHICKEN_BLOCK.get(), context -> new ToyChicaChickenBlockTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.WITHERED_FREDDY_BLOCK.get(), context -> new WitheredFreddyBlockTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.RETRO_FREDDY_BLOCK.get(), context -> new RetroFreddyBlockTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.WITHERED_BONNIE_BLOCK.get(), context -> new WitheredBonnieBlockTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.RETRO_BONNIE_BLOCK.get(), context -> new RetroBonnieBlockTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.FREDBEAR_BLOCK.get(), context -> new FredbearBlockTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.FREDBEAR_01_BLOCK.get(), context -> new Fredbear01BlockTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.CONTROL_PANEL.get(), context -> new ControlPanelTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.BREAKER_CONTROL.get(), context -> new BreakerControlTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.LARGE_FAN.get(), context -> new LargeFanTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.SCOOPER.get(), context -> new ScooperTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.DEACTIVATED_BABY.get(), context -> new DeactivatedBabyTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.DEACTIVATED_FUNTIME_FREDDY.get(), context -> new DeactivatedFuntimeFreddyTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.DEACTIVATED_BALLORA.get(), context -> new DeactivatedBalloraTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.PIECES_FUNTIME_FREDDY.get(), context -> new PiecesFuntimeFreddyTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.PIECES_FUNTIME_FOXY.get(), context -> new PiecesFuntimeFoxyTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.PIECES_BALLORA.get(), context -> new PiecesBalloraTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.EXOTIC_BUTTER_BASKET.get(), context -> new ExoticButterBasketTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.EMPTY_EXOTIC_BUTTER_BASKET.get(), context -> new EmptyExoticButterBasketTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.PIZZERIA_SIGN_BABYS.get(), context -> new PizzeriaSignBabysTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.PIZZERIA_SIGN_BABYS_ALT.get(), context -> new PizzeriaSignBabysAltTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.PIZZERIA_SIGN_CHICAS.get(), context -> new PizzeriaSignChicasTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.PUPPET_BLOCK.get(), context -> new PuppetBlockTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.TOY_FOXY_BLOCK.get(), context -> new ToyFoxyBlockTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.WITHERED_CHICA_BLOCK.get(), context -> new WitheredChicaBlockTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.RETRO_CHICA_BLOCK.get(), context -> new RetroChicaBlockTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.CUTOUT_FREDBEAR_ICECREAM.get(), context -> new CutoutFredbearIcecreamTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.BALLOON_BARREL.get(), context -> new BalloonBarrelTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.DISCOUNT_BALLPIT.get(), context -> new DiscountBallpitTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.SANITATION_STATION.get(), context -> new SanitationStationTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.DISCOUNT_COOLING_UNIT.get(), context -> new DiscountCoolingUnitTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.DUCK_POND.get(), context -> new DuckPondTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.PIN_THE_BOWTIE_FREDDY.get(), context -> new PinTheBowtieFreddyTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.PIN_THE_BOWTIE_TOY_FREDDY.get(), context -> new PinTheBowtieToyFreddyTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.CAR_PURPLE_CHEVROLET_IMPALA_BLOCK.get(), context -> new CarPurpleChevroletImpalaBlockTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.ENHANCED_SPEAKER.get(), context -> new EnhancedSpeakerTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.DELUXE_SPEAKER.get(), context -> new DeluxeSpeakerTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.ARCADE_FRUITY_MAZE.get(), context -> new ArcadeFruityMazeTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.ARCADE_MIDNIGHT_MOTORIST.get(), context -> new ArcadeMidnightMotoristTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.STAR_ARCH.get(), context -> new StarArchTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.NOVELTY_TRAFFIC_LIGHT.get(), context -> new NoveltyTrafficLightTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.CANDY_CADET.get(), context -> new CandyCadetTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.SHOP_SIGN_DUMPSTER_DIVER.get(), context -> new ShopSignDumpsterDiverTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.CONCERT_SPEAKER.get(), context -> new ConcertSpeakerTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.NEON_STAGE_LIGHT_GREEN.get(), context -> new NeonStageLightGreenTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.NEON_STAGE_LIGHT_BLUE.get(), context -> new NeonStageLightBlueTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.NEON_STAGE_LIGHT_PINK.get(), context -> new NeonStageLightPinkTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.NEON_STAGE_LIGHT_ORANGE.get(), context -> new NeonStageLightOrangeTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.CAR_DODGE_RAM_1982_BLOCK.get(), context -> new CarDodgeRam1982BlockTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.BALLPIT_TOWER.get(), context -> new BallpitTowerTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.RETRO_FOXY_BLOCK.get(), context -> new RetroFoxyBlockTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.WITHERED_FOXY_BLOCK.get(), context -> new WitheredFoxyBlockTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.CARNIVAL_HOOPS.get(), context -> new CarnivalHoopsTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.LADDER_TOWER.get(), context -> new LadderTowerTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.RIDING_ROCKET_RED.get(), context -> new RidingRocketRedTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.RIDING_ROCKET_PURPLE.get(), context -> new RidingRocketPurpleTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.CLOWN_LEMONADE.get(), context -> new ClownLemonadeTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.CLOWN_FRUIT_PUNCH.get(), context -> new ClownFruitPunchTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.NEON_JUKEBOX.get(), context -> new NeonJukeboxTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.MEDICAL_STATION.get(), context -> new MedicalStationTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.BLAST_SECURITY_DOOR.get(), context -> new BlastSecurityDoorTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.PIZZERIA_SIGN_FFPS.get(), context -> new PizzeriaSignFfpsTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.PIZZERIA_SIGN_MOVIE.get(), context -> new PizzeriaSignMovieTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.PIZZERIA_SIGN_MOVIE_2.get(), context -> new PizzeriaSignMovie2TileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.BALLOON_CART.get(), context -> new BalloonCartTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.DELUXE_BALLPIT.get(), context -> new DeluxeBallpitTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.EGG_BABY.get(), context -> new EggBabyTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.GRAVITY_VORTEX.get(), context -> new GravityVortexTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.PRIZE_KING.get(), context -> new PrizeKingTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.SECURITY_PUPPET_PROP.get(), context -> new SecurityPuppetPropTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.CIRCUS_BABY_CLOCK.get(), context -> new CircusBabyClockTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.BALLPIT_ROTTEN.get(), context -> new BallpitRottenTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.BALLPIT_VINTAGE.get(), context -> new BallpitVintageTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.CUTOUT_FREDDY_RETRO.get(), context -> new CutoutFreddyRetroTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.FAZCOINS_5.get(), context -> new Fazcoins5TileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.FAZCOINS_25.get(), context -> new Fazcoins25TileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.FAZCOINS_100.get(), context -> new Fazcoins100TileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.FAZCOINS_1000.get(), context -> new Fazcoins1000TileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.FAZCOINS_10000.get(), context -> new Fazcoins10000TileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.CAMERA.get(), context -> new CameraTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.BROKEN_FREDDY.get(), context -> new BrokenFreddyTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.BROKEN_BONNIE.get(), context -> new BrokenBonnieTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.BROKEN_CHICA.get(), context -> new BrokenChicaTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.BROKEN_FOXY.get(), context -> new BrokenFoxyTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.CUTOUT_FREDBEAR_BITTEN.get(), context -> new CutoutFredbearBittenTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.CUTOUT_SPRINGBONNIE_ROTTEN.get(), context -> new CutoutSpringbonnieRottenTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.NEON_SIGN_KITCHEN.get(), context -> new NeonSignKitchenTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.NEON_SIGN_ARCADE.get(), context -> new NeonSignArcadeTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.PIZZA_BOX_1985.get(), context -> new PizzaBox1985TileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.PIZZA_BOX_1985_EMPTY.get(), context -> new PizzaBox1985EmptyTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.PIZZA_BOX_1987.get(), context -> new PizzaBox1987TileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.PIZZA_BOX_1987_EMPTY.get(), context -> new PizzaBox1987EmptyTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.PIZZA_BOX_1987_ALT.get(), context -> new PizzaBox1987AltTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.PIZZA_BOX_1987_ALT_EMPTY.get(), context -> new PizzaBox1987AltEmptyTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.PIZZA_BOX_2023.get(), context -> new PizzaBox2023TileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.PIZZA_BOX_2023_EMPTY.get(), context -> new PizzaBox2023EmptyTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.NEON_SIGN_PARTY_ROOM.get(), context -> new NeonSignPartyRoomTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.NEON_SIGN_RESTROOM.get(), context -> new NeonSignRestroomTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.SPRINGBONNIE_BLOCK.get(), context -> new SpringbonnieBlockTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.SPRINGBONNIE_BLOCK_01.get(), context -> new SpringbonnieBlock01TileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.PROJECTOR.get(), context -> new ProjectorTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.CUTOUT_BONNIE_RETRO.get(), context -> new CutoutBonnieRetroTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.CUTOUT_CHICA_RETRO.get(), context -> new CutoutChicaRetroTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.CUTOUT_FOXY_RETRO.get(), context -> new CutoutFoxyRetroTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.CUTOUT_HELPY.get(), context -> new CutoutHelpyTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.BONK_A_BON.get(), context -> new BonkABonTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.PINBALL_TOY_FREDDY.get(), context -> new PinballToyFreddyTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.PINBALL_TOY_BONNIE.get(), context -> new PinballToyBonnieTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.PINBALL_TOY_CHICA.get(), context -> new PinballToyChicaTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.PINBALL_TOY_FOXY.get(), context -> new PinballToyFoxyTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.RASC_BLOCK.get(), context -> new RascBlockTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.GARFELD.get(), context -> new GarfeldTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.TOYPUG.get(), context -> new ToypugTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.ROSIE.get(), context -> new RosieTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.CAR_FAZVAN_BLOCK.get(), context -> new CarFazvanBlockTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.FRYER.get(), context -> new FryerTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.FRYING_PAN.get(), context -> new FryingPanTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.POT.get(), context -> new PotTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.FAZ_OVEN.get(), context -> new FazOvenTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.BOX_PLATES.get(), context -> new BoxPlatesTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.BOX_ENDO.get(), context -> new BoxEndoTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.BOX_PLUSH_1.get(), context -> new BoxPlush1TileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.BOX_PLUSH_2.get(), context -> new BoxPlush2TileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.BOX_PLUSH_3.get(), context -> new BoxPlush3TileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.BOX_PLUSH_4.get(), context -> new BoxPlush4TileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.PIZZERIA_SIGN_1987.get(), context -> new PizzeriaSign1987TileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.PIZZERIA_SIGN_FRIGHTS.get(), context -> new PizzeriaSignFrightsTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.PIZZERIA_SIGN_FREDBEARS.get(), context -> new PizzeriaSignFredbearsTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.SHOP_SIGN_STANS_BUDGET_TECH.get(), context -> new ShopSignStansBudgetTechTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.SHOP_SIGN_SMILES_AND_SERVOS.get(), context -> new ShopSignSmilesAndServosTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.SHOP_SIGN_RARE_FINDS_AUCTION.get(), context -> new ShopSignRareFindsAuctionTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.BIG_SECURITY_DOOR.get(), context -> new BigSecurityDoorTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.CAROUSEL_FREDDY.get(), context -> new CarouselFreddyTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.CAROUSEL_FREDDY_TOY.get(), context -> new CarouselFreddyToyTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.CAROUSEL_FREDDY_RETRO.get(), context -> new CarouselFreddyRetroTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.CAROUSEL_FREDBEAR.get(), context -> new CarouselFredbearTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.DUMPSTER_GREEN.get(), context -> new DumpsterGreenTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.DUMPSTER_BLUE.get(), context -> new DumpsterBlueTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.STAGE_SUN_CREEP.get(), context -> new StageSunCreepTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.STAGE_MOON_CREEP.get(), context -> new StageMoonCreepTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.TRASH_CAN_FREDDY.get(), context -> new TrashCanFreddyTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.TRASH_CAN_BONNIE.get(), context -> new TrashCanBonnieTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.TRASH_CAN_CHICA.get(), context -> new TrashCanChicaTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.TRASH_CAN_FOXY.get(), context -> new TrashCanFoxyTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.TRASH_CAN_CUPCAKE.get(), context -> new TrashCanCupcakeTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.CAR_FAZVAN_PROP.get(), context -> new CarFazvanPropTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.CAR_STATION_WAGON_BLOCK.get(), context -> new CarStationWagonBlockTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.TRASH_BAG_GREEN.get(), context -> new TrashBagGreenTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.TRASH_BAG_BLACK.get(), context -> new TrashBagBlackTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.TRASH.get(), context -> new TrashTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.BULLETIN_BOARD.get(), context -> new BulletinBoardTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.LAPTOP_OLD.get(), context -> new LaptopOldTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.LAPTOP.get(), context -> new LaptopTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.OLD_MAN_CONSEQUENCES_BLOCK.get(), context -> new OldManConsequencesBlockTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.FRIDGE_WHITE.get(), context -> new FridgeWhiteTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.FRIDGE_GRAY.get(), context -> new FridgeGrayTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.VAN_RIDE.get(), context -> new VanRideTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.OFFICE_CHAIR_RED.get(), context -> new OfficeChairRedTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.OFFICE_CHAIR_BLACK.get(), context -> new OfficeChairBlackTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.PIZZA_BOX_STACK_1988.get(), context -> new PizzaBoxStack1988TileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.PIZZA_BOX_STACK_1979.get(), context -> new PizzaBoxStack1979TileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.PIZZA_BOX_STACK_1985.get(), context -> new PizzaBoxStack1985TileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.PIZZA_BOX_STACK_1987.get(), context -> new PizzaBoxStack1987TileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.PIZZA_BOX_STACK_1987_ALT.get(), context -> new PizzaBoxStack1987AltTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.PIZZA_BOX_STACK_2023.get(), context -> new PizzaBoxStack2023TileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.SKEEBALL_GENERIC.get(), context -> new SkeeballGenericTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.SKEEBALL_PIZZAROLLER.get(), context -> new SkeeballPizzarollerTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.BATHROOM_STALL.get(), context -> new BathroomStallTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.CLOCK_WALL.get(), context -> new ClockWallTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.CLOCK_WALL_FREDDY.get(), context -> new ClockWallFreddyTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.CLOCK_WALL_BONNIE.get(), context -> new ClockWallBonnieTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.CLOCK_WALL_CHICA.get(), context -> new ClockWallChicaTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.CLOCK_WALL_FOXY.get(), context -> new ClockWallFoxyTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.CLOCK_WALL_TOY_FREDDY.get(), context -> new ClockWallToyFreddyTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.CLOCK_WALL_TOY_BONNIE.get(), context -> new ClockWallToyBonnieTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.CLOCK_WALL_TOY_CHICA.get(), context -> new ClockWallToyChicaTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.CLOCK_WALL_TOY_FOXY.get(), context -> new ClockWallToyFoxyTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.CLOCK_WALL_FREDBEAR.get(), context -> new ClockWallFredbearTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.CLOCK_WALL_SPRINGBONNIE.get(), context -> new ClockWallSpringbonnieTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.TRASH_CAN_MESH.get(), context -> new TrashCanMeshTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.CLAW_MACHINE_PIZZA_PARTY.get(), context -> new ClawMachinePizzaPartyTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.CLAW_MACHINE_CUPCAKE_BONANZA.get(), context -> new ClawMachineCupcakeBonanzaTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.SINK_KITCHEN.get(), context -> new SinkKitchenTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.CUTOUT_TREE_OAK.get(), context -> new CutoutTreeOakTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.CUTOUT_TREE_PINE.get(), context -> new CutoutTreePineTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.CUTOUT_TREE_PALM.get(), context -> new CutoutTreePalmTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.STAGE_LIGHT_RED.get(), context -> new StageLightRedTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.STAGE_LIGHT_ORANGE.get(), context -> new StageLightOrangeTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.STAGE_LIGHT_YELLOW.get(), context -> new StageLightYellowTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.STAGE_LIGHT_GREEN.get(), context -> new StageLightGreenTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.STAGE_LIGHT_BLUE.get(), context -> new StageLightBlueTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.STAGE_LIGHT_PURPLE.get(), context -> new StageLightPurpleTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.STAGE_LIGHT_PINK.get(), context -> new StageLightPinkTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.FRIDGE_INDUSTRIAL.get(), context -> new FridgeIndustrialTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.FREDBEAR_BLOODY_BLOCK.get(), context -> new FredbearBloodyBlockTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.FREDBEAR_BLOODY_WRAP_BLOCK.get(), context -> new FredbearBloodyWrapBlockTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.BIG_BACKSTAGE_DOOR.get(), context -> new BigBackstageDoorTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.BIG_BACKSTAGE_DOOR_2.get(), context -> new BigBackstageDoor2TileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.BIG_KITCHEN_DOOR.get(), context -> new BigKitchenDoorTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.BIG_KITCHEN_WHITE_DOOR.get(), context -> new BigKitchenWhiteDoorTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.BIG_BEDROOM_DOOR.get(), context -> new BigBedroomDoorTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.BIG_RENTAL_DOOR.get(), context -> new BigRentalDoorTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.BIG_RENTAL_WINDOWED_DOOR.get(), context -> new BigRentalWindowedDoorTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.BIG_ENTRANCE_RED_DOOR.get(), context -> new BigEntranceRedDoorTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.BIG_BACKSTAGE_DOOR_RED.get(), context -> new BigBackstageDoorRedTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.BIG_ENTRANCE_DOOR.get(), context -> new BigEntranceDoorTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.BIG_ENTRANCE_RED_GLASS_DOOR.get(), context -> new BigEntranceRedGlassDoorTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.BIG_EXIT_DOOR.get(), context -> new BigExitDoorTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.BIG_KITCHEN_DOOR_WIDE.get(), context -> new BigKitchenDoorWideTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.BIG_KITCHEN_WHITE_DOOR_WIDE.get(), context -> new BigKitchenWhiteDoorWideTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.BIG_ENTRANCE_DOOR_WIDE.get(), context -> new BigEntranceDoorWideTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.BIG_ENTRANCE_RED_GLASS_DOOR_WIDE.get(), context -> new BigEntranceRedGlassDoorWideTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.BIG_ENTRANCE_RED_DOOR_WIDE.get(), context -> new BigEntranceRedDoorWideTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.BIG_BACKSTAGE_RED_DOOR_WIDE.get(), context -> new BigBackstageRedDoorWideTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.BIG_OFFICE_DOOR_WINDOWED_1.get(), context -> new BigOfficeDoorWindowed1TileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.BIG_OFFICE_DOOR_WINDOWED_2.get(), context -> new BigOfficeDoorWindowed2TileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.BIG_CLOSET.get(), context -> new BigClosetTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.HAPPY_FROG_BLOCK.get(), context -> new HappyFrogBlockTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.MR_HIPPO_BLOCK.get(), context -> new MrHippoBlockTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.NEDDBEAR_BLOCK.get(), context -> new NeddbearBlockTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.PIGPATCH_BLOCK.get(), context -> new PigpatchBlockTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.ORVILLE_ELEPHANT_BLOCK.get(), context -> new OrvilleElephantBlockTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.CAR_HARLEY_MOTORCYCLE_BLOCK.get(), context -> new CarHarleyMotorcycleBlockTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.ROCKSTAR_FREDDY_BLOCK.get(), context -> new RockstarFreddyBlockTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.ROCKSTAR_BONNIE_BLOCK.get(), context -> new RockstarBonnieBlockTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.ROCKSTAR_CHICA_BLOCK.get(), context -> new RockstarChicaBlockTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.ROCKSTAR_FOXY_BLOCK.get(), context -> new RockstarFoxyBlockTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.LEFTY_BLOCK.get(), context -> new LeftyBlockTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.CUTOUT_FREDDY_TOY.get(), context -> new CutoutFreddyToyTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.CUTOUT_BONNIE_TOY.get(), context -> new CutoutBonnieToyTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.CUTOUT_CHICA_TOY.get(), context -> new CutoutChicaToyTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.CUTOUT_FOXY_FUNTIME.get(), context -> new CutoutFoxyFuntimeTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.CUTOUT_FREDDY_FUNTIME.get(), context -> new CutoutFreddyFuntimeTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.CUTOUT_BABY.get(), context -> new CutoutBabyTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.CUTOUT_BALLORA.get(), context -> new CutoutBalloraTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.BIG_ELEVATOR_DOOR.get(), context -> new BigElevatorDoorTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.DITTOPHOBIA_FREDDY_BLOCK.get(), context -> new DittophobiaFreddyBlockTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.DITTOPHOBIA_BONNIE_BLOCK.get(), context -> new DittophobiaBonnieBlockTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.DITTOPHOBIA_CHICA_BLOCK.get(), context -> new DittophobiaChicaBlockTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.DITTOPHOBIA_FOXY_BLOCK.get(), context -> new DittophobiaFoxyBlockTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.ENDO_01_BLOCK.get(), context -> new Endo01BlockTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.RUSTY_BLOCK.get(), context -> new RustyBlockTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.ENDO_02_BLOCK.get(), context -> new Endo02BlockTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.CAR_POLICE_CRUISER_CHEVROLET_IMPALA_1983_BLOCK.get(), context -> new CarPoliceCruiserChevroletImpala1983BlockTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.FUNTIME_DELILAH_BLOCK.get(), context -> new FuntimeDelilahBlockTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.FUNTIME_FREDDY_BLOCK.get(), context -> new FuntimeFreddyBlockTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.CIRCUS_BABY_BLOCK.get(), context -> new CircusBabyBlockTileRenderer());
		event.registerBlockEntityRenderer(YaFnafmodModBlockEntities.BALLORA_BLOCK.get(), context -> new BalloraBlockTileRenderer());
	}
}
